syntax on
set nu
set rnu
set cursorline
set hlsearch
set incsearch
set smartcase
set ignorecase

let mapleader = " "
nnoremap Q :q<cr>
nnoremap S :w<cr>
nnoremap <leader>sl :nohlsearch<cr>

" Change cursor style in different mode
let &t_SI = "\<Esc>]50;CursorShape=1\x7"
let &t_SR = "\<Esc>]50;CursorShape=2\x7"
let &t_EI = "\<Esc>]50;CursorShape=0\x7"
